# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: m:/Documents/hdmi-in/hdmi-in.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_s00_data_fifo_0/hdmi_in_s00_data_fifo_0.xci
# IP: The module: 'hdmi_in_s00_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: m:/Documents/hdmi-in/hdmi-in.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_s00_data_fifo_0/hdmi_in_s00_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_in_s00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: m:/Documents/hdmi-in/hdmi-in.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_s00_data_fifo_0/hdmi_in_s00_data_fifo_0.xci
# IP: The module: 'hdmi_in_s00_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: m:/Documents/hdmi-in/hdmi-in.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_s00_data_fifo_0/hdmi_in_s00_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_in_s00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
